---
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "./src/scripts/release.sh ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - src/module.json
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - - "@semantic-release/github"
    - assets:
        - dist/module.json
        - dist/xdy-module-template.zip
preset: angular
branches: [ '+([0-9])?(.{+([0-9]),x}).x', 'master', { name: 'foundry-0.81', prerelease: true } ]
